"""Add user-thumb feedback column to ``usage_logs``.

Stage-16 row 19. Adds a single nullable ``feedback`` text column
that stores the user's 👍 / 👎 verdict on the AI reply paired with
each ``usage_logs`` row. Allowed values:

* ``'positive'`` — user tapped 👍.
* ``'negative'`` — user tapped 👎.
* ``NULL`` — user has not voted (the default; backfill is skipped).

Why ``TEXT`` rather than an ENUM:

* Postgres ENUMs lock the operator into a hard-flag-day rotation
  if we ever want to add an "other" / "needs review" value (the
  ``ALTER TYPE ... ADD VALUE`` is non-transactional, which means
  it can't run inside an Alembic migration that also mutates a
  table). A varchar with a CHECK is just as compact at storage
  time (Postgres TOAST-compresses both equally) and trivially
  extensible.

* The CHECK constraint pins the value space at the DB layer so
  a buggy caller (or a hand-rolled UPDATE from psql) can't
  smuggle a ``"PoSiTiVe"`` row into the table that then breaks
  the dissatisfaction-rate aggregate.

Why a partial covering index on ``(model_used, created_at DESC)
WHERE feedback IS NOT NULL``:

* The dissatisfaction-rate aggregate (queried from
  ``ai_feedback.dissatisfaction_alert_loop``) sums ``COUNT(*)``
  and ``COUNT(feedback = 'negative')`` *per-model* over a
  trailing window. Without the partial index, the planner would
  do a sequential scan of the whole ``usage_logs`` table — which
  on the live deploy is already 3 M+ rows after a year. Most of
  those rows have ``feedback IS NULL`` (the user just didn't
  vote), so a partial index narrows the scan to the small
  fraction of rated rows.

* The ``DESC`` ordering matches the alert loop's
  ``WHERE created_at >= NOW() - INTERVAL ...`` filter so the
  index is range-scanned forward from the cutoff.

Idempotent: both upgrade and downgrade are guarded with ``IF
(NOT) EXISTS`` so a partially-applied migration in a dev sandbox
can be re-run without manual cleanup. The CHECK constraint name
is fixed (rather than auto-generated by Postgres) so the
downgrade can drop it explicitly without first SELECT-ing
``pg_constraint``.

Revision ID: 0020_usage_logs_feedback
Revises: 0019_disabled_model_per_gateway
"""

from alembic import op

revision = "0020_usage_logs_feedback"
down_revision = "0019_disabled_model_per_gateway"
branch_labels = None
depends_on = None


UPGRADE_SQL = """\
ALTER TABLE usage_logs
    ADD COLUMN IF NOT EXISTS feedback TEXT NULL;

-- The CHECK lives separately (with a fixed name) so the
-- downgrade can target it by name without first SELECT-ing
-- ``pg_constraint``. Postgres' ``ALTER TABLE ... ADD CONSTRAINT``
-- does NOT support ``IF NOT EXISTS``, so for idempotent re-runs
-- (a dev sandbox that ran the upgrade halfway and then crashed)
-- we DROP the constraint first and ADD it back. The DROP is a
-- no-op on a fresh database (``IF EXISTS`` short-circuits) and
-- prevents the ADD from raising on a re-run.
ALTER TABLE usage_logs
    DROP CONSTRAINT IF EXISTS usage_logs_feedback_check;
ALTER TABLE usage_logs
    ADD CONSTRAINT usage_logs_feedback_check
        CHECK (feedback IS NULL OR feedback IN ('positive', 'negative'));

CREATE INDEX IF NOT EXISTS idx_usage_logs_feedback_model_created
    ON usage_logs (model_used, created_at DESC)
    WHERE feedback IS NOT NULL;
"""


DOWNGRADE_SQL = """\
DROP INDEX IF EXISTS idx_usage_logs_feedback_model_created;
ALTER TABLE usage_logs
    DROP CONSTRAINT IF EXISTS usage_logs_feedback_check;
ALTER TABLE usage_logs
    DROP COLUMN IF EXISTS feedback;
"""


def upgrade() -> None:
    op.execute(UPGRADE_SQL)


def downgrade() -> None:
    op.execute(DOWNGRADE_SQL)
